# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user1 = User.create(email: "guest@aa.io", username: "Guest", password: "tourneygen")
user2 = User.create(email: "lmb@aa.io", username: "LiMuBai", password: "hiddentigers")
user3 = User.create(email: "ysl@aa.io", username: "YuShuLien", password: "crouchingdragons")
user4 = User.create(email: "plf@aa.io", username: "PeteLaFleur", password: "waytooaverage")
user5 = User.create(email: "wg@aa.io", username: "WhiteGoodman", password: "globogym")
user6 = User.create(email: "bobby@aa.io", username: "Bobby", password: "weirdpassword")
user7 = User.create(email: "mml@aa.io", username: "ManMythLegend", password: "themanthemyththelegend")
user8 = User.create(email: "chucknorris@aa.io", username: "ChuckNorris", password: "chucknorrismemes")
# user9 = User.create(email: "bobby@aa.io", username: "Bobby", password: "weirdpassword")
# user10 = User.create(email: "bobby@aa.io", username: "Bobby", password: "weirdpassword")
tourn1 = Tournament.create(title: "1st Tournament Tutorial", author_id: user1.id, description: "Welcome to the first tournament ever hosted on TournaGen! This is an example of a tournament starting from scratch. Take a look around!", max_teams: 32)
tourn2 = Tournament.create(title: "Good Ol' Game of Dodgeball", author_id: user2.id, description: "Welcome to the second tournament!", max_teams: 16)
team1 = Team.create(name: "Beach Bums", owner_id: user1.id, description: "First Team")
team2 = Team.create(name: "Crouching Tigers", owner_id: user2.id, description: "Second Team")
team3 = Team.create(name: "Hidden Dragons", owner_id: user3.id, description: "Third Team")
team4 = Team.create(name: "Average Joe's", owner_id: user4.id, description: "Average Joe's is a local team named under the gym they are trying to save from bankruptcy. Led by its owner Pete LaFleur and coached by dodgeball legend 'Patches' O'Houlihan")
team5 = Team.create(name: "Purple Cobras", owner_id: user5.id, description: "Fifth Team")
team6 = Team.create(name: "Bobby's World", owner_id: user6.id, description: "Sixth Team")
team7 = Team.create(name: "Legends", owner_id: user7.id, description: "Seventh Team")
team8 = Team.create(name: "Chuck Norris Jokes", owner_id: user8.id, description: "Eighth Team")
reg1 = Registration.create(tournament_id: tourn1.id, team_id: team2.id)
reg2 = Registration.create(tournament_id: tourn1.id, team_id: team3.id)
reg3 = Registration.create(tournament_id: tourn1.id, team_id: team4.id)
reg4 = Registration.create(tournament_id: tourn1.id, team_id: team5.id)
reg5 = Registration.create(tournament_id: tourn1.id, team_id: team6.id)
reg6 = Registration.create(tournament_id: tourn1.id, team_id: team7.id)
reg7 = Registration.create(tournament_id: tourn1.id, team_id: team8.id)
reg8 = Registration.create(tournament_id: tourn2.id, team_id: team2.id)
reg9 = Registration.create(tournament_id: tourn2.id, team_id: team3.id)
reg10 = Registration.create(tournament_id: tourn2.id, team_id: team4.id)
reg11 = Registration.create(tournament_id: tourn2.id, team_id: team5.id)
reg12 = Registration.create(tournament_id: tourn2.id, team_id: team6.id)
reg13 = Registration.create(tournament_id: tourn2.id, team_id: team7.id)
reg14 = Registration.create(tournament_id: tourn2.id, team_id: team8.id)
